//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        /// <summary>
        /// Tệp log ghi lại quá trình nhận dạng và phân tích
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Tệp log ghi lại quá trình nhận dạng và phân tích")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("nhatky.txt")]
        public string InterpretLogFile {
            get {
                return ((string)(this["InterpretLogFile"]));
            }
        }
        
        /// <summary>
        /// Số câu hỏi tối đa có thể có trong đề.
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Số câu hỏi tối đa có thể có trong đề.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public int MaximumQuestion {
            get {
                return ((int)(this["MaximumQuestion"]));
            }
        }
        
        /// <summary>
        /// Ký tự hiển thị nếu không có phương án trả lời nào được chọn
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Ký tự hiển thị nếu không có phương án trả lời nào được chọn")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("X")]
        public char BlankChar {
            get {
                return ((char)(this["BlankChar"]));
            }
        }
        
        /// <summary>
        /// Tệp quan trọng, chứa dữ liệu về lớp, danh sách HS. Setting này lưu vị trí của tệp tin đó.
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Tệp quan trọng, chứa dữ liệu về lớp, danh sách HS. Setting này lưu vị trí của tệp" +
            " tin đó.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("groups.malyst.xml")]
        public string GroupsFile {
            get {
                return ((string)(this["GroupsFile"]));
            }
        }
        
        /// <summary>
        /// Độ phân giải quét mặc định
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Độ phân giải quét mặc định")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public float DefaultDpi {
            get {
                return ((float)(this["DefaultDpi"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Malyst Scan")]
        public string WindowCaption {
            get {
                return ((string)(this["WindowCaption"]));
            }
        }
        
        /// <summary>
        /// Filter dùng để lọc ra tệp chứa đáp án/bộ đáp án
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Filter dùng để lọc ra tệp chứa đáp án/bộ đáp án")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Bộ đáp án của Malyst|*.key.xml|Tất cả các tệp|*.*")]
        public string KeyFileFilter {
            get {
                return ((string)(this["KeyFileFilter"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Kết quả chấm điểm của Malyst|*.log.xml|Tất cả các tệp|*.*")]
        public string LogFileFilter {
            get {
                return ((string)(this["LogFileFilter"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Xem trước khi in")]
        public string PrintPreviewCaption {
            get {
                return ((string)(this["PrintPreviewCaption"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Times New Roman, 11pt")]
        public global::System.Drawing.Font DefaultPrintFont {
            get {
                return ((global::System.Drawing.Font)(this["DefaultPrintFont"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ảnh quét |*.tif;*.jpg;*.bmp|Tất cả các tệp|*.*")]
        public string ImageFileFilter {
            get {
                return ((string)(this["ImageFileFilter"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.8")]
        public float RequireFillCoefficient {
            get {
                return ((float)(this["RequireFillCoefficient"]));
            }
        }
        
        /// <summary>
        /// Thang điểm
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Thang điểm")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int MarkTheme {
            get {
                return ((int)(this["MarkTheme"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("230")]
        public int PencilThreshold {
            get {
                return ((int)(this["PencilThreshold"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("160")]
        public int BlackWhiteThreshold {
            get {
                return ((int)(this["BlackWhiteThreshold"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ABCD")]
        public string KeySymbol {
            get {
                return ((string)(this["KeySymbol"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("suites.malyst.xml")]
        public string SuiteFile {
            get {
                return ((string)(this["SuiteFile"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("GradientActiveCaption")]
        public global::System.Drawing.Color ColorHilight {
            get {
                return ((global::System.Drawing.Color)(this["ColorHilight"]));
            }
        }
        
        /// <summary>
        /// Thư mục lưu kết quả của quá trình tiền xử lý
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Thư mục lưu kết quả của quá trình tiền xử lý")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\Malyst Data")]
        public string PreprocessFolder {
            get {
                return ((string)(this["PreprocessFolder"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float AnchorRadius {
            get {
                return ((float)(this["AnchorRadius"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25.4")]
        public float dConvertValueRatio {
            get {
                return ((float)(this["dConvertValueRatio"]));
            }
        }
        
        /// <summary>
        /// (BaseLength) Khoảng cách giữa top-left và bottom left, dùng để tính scale. Độ dài tính theo chiều dài ô cơ sở
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("(BaseLength) Khoảng cách giữa top-left và bottom left, dùng để tính scale. Độ dài" +
            " tính theo chiều dài ô cơ sở")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public float dHorizonalAnchorDistanceByBase {
            get {
                return ((float)(this["dHorizonalAnchorDistanceByBase"]));
            }
        }
        
        /// <summary>
        /// (mm) Độ dài cơ sở: là chiều dài ô hình vuông chứa ở tâm nó ô tick. Đây cũng là độ dài dùng để tính toán chính khi xác định vị trí
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("(mm) Độ dài cơ sở: là chiều dài ô hình vuông chứa ở tâm nó ô tick. Đây cũng là độ" +
            " dài dùng để tính toán chính khi xác định vị trí")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public float dBaseLength {
            get {
                return ((float)(this["dBaseLength"]));
            }
        }
        
        /// <summary>
        /// (BaseLength) tọa độ X.  Khoảng cách từ TL đến tâm tick A của câu số 1. Dùng để tính tọa độ Root
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("(BaseLength) tọa độ X.  Khoảng cách từ TL đến tâm tick A của câu số 1. Dùng để tí" +
            "nh tọa độ Root")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.5")]
        public float dRootOffsetByX {
            get {
                return ((float)(this["dRootOffsetByX"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3.5")]
        public float dRootOffsetByY {
            get {
                return ((float)(this["dRootOffsetByY"]));
            }
        }
        
        /// <summary>
        /// Cột 1: STT câu hỏi đầu tiên
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Cột 1: STT câu hỏi đầu tiên")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int C1_StartNo {
            get {
                return ((int)(this["C1_StartNo"]));
            }
        }
        
        /// <summary>
        /// Cột 1: STT câu hỏi cuối cùng
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Cột 1: STT câu hỏi cuối cùng")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("17")]
        public int C1_EndNo {
            get {
                return ((int)(this["C1_EndNo"]));
            }
        }
        
        /// <summary>
        /// Cột 2: STT câu hỏi đầu tiên
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Cột 2: STT câu hỏi đầu tiên")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("18")]
        public int C2_StartNo {
            get {
                return ((int)(this["C2_StartNo"]));
            }
        }
        
        /// <summary>
        /// Cột 2: STT câu hỏi cuối cùng
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Cột 2: STT câu hỏi cuối cùng")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("33")]
        public int C2_EndNo {
            get {
                return ((int)(this["C2_EndNo"]));
            }
        }
        
        /// <summary>
        /// Cột 3: STT câu hỏi đầu tiên
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Cột 3: STT câu hỏi đầu tiên")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("34")]
        public int C3_StartNo {
            get {
                return ((int)(this["C3_StartNo"]));
            }
        }
        
        /// <summary>
        /// Cột 3: STT câu hỏi cuối cùng
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Cột 3: STT câu hỏi cuối cùng")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int C3_EndNo {
            get {
                return ((int)(this["C3_EndNo"]));
            }
        }
        
        /// <summary>
        /// Tính offset của cột kể từ root (tâm tick A của câu 1)
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Tính offset của cột kể từ root (tâm tick A của câu 1)")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float C1_Xoffset {
            get {
                return ((float)(this["C1_Xoffset"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float C1_Yoffset {
            get {
                return ((float)(this["C1_Yoffset"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public float C2_Xoffset {
            get {
                return ((float)(this["C2_Xoffset"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float C2_Yoffset {
            get {
                return ((float)(this["C2_Yoffset"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12")]
        public float C3_Xoffset {
            get {
                return ((float)(this["C3_Xoffset"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float C3_Yoffset {
            get {
                return ((float)(this["C3_Yoffset"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("18")]
        public float CStudent_Xoffset {
            get {
                return ((float)(this["CStudent_Xoffset"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("11")]
        public float CProblem_Yoffset {
            get {
                return ((float)(this["CProblem_Yoffset"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public float CStudent_Yoffset {
            get {
                return ((float)(this["CStudent_Yoffset"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("18")]
        public float CProblem_Xoffset {
            get {
                return ((float)(this["CProblem_Xoffset"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("18")]
        public float CGroup_Xoffset {
            get {
                return ((float)(this["CGroup_Xoffset"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("17")]
        public float CGroup_Yoffset {
            get {
                return ((float)(this["CGroup_Yoffset"]));
            }
        }
        
        /// <summary>
        /// Số dòng trong một trang in
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Số dòng trong một trang in")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public int PrintRows {
            get {
                return ((int)(this["PrintRows"]));
            }
        }
        
        /// <summary>
        /// Kiểu chữ dùng khi in
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Kiểu chữ dùng khi in")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Times New Roman, 12pt")]
        public global::System.Drawing.Font PrintFont {
            get {
                return ((global::System.Drawing.Font)(this["PrintFont"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("80")]
        public int PrintMargin {
            get {
                return ((int)(this["PrintMargin"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Định dạng RTF cho Word|*.rtf|Tất cả các tệp|*.*")]
        public string FilterRtf {
            get {
                return ((string)(this["FilterRtf"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("23")]
        public int PrintRowsWithName {
            get {
                return ((int)(this["PrintRowsWithName"]));
            }
        }
    }
}
